'use client'

import '@lunagraph/editor/styles.css';
import { LunagraphEditor } from "@lunagraph/editor";
import * as lunagraph from '../../.lunagraph/components';
// Import snapshots - generated by dev-server when editing components
import { snapshots } from '../../.lunagraph/snapshots';

export default function Editor() {
  return <LunagraphEditor {...lunagraph} snapshots={snapshots} />
}
