// Auto-generated by @lunagraph/dev-server - do not edit manually
// This file is updated when snapshots are created or modified

import type { ComponentType } from 'react'
import AddFilterButtonSnapshot from './AddFilterButton.snapshot'
import AdvancedFilterSnapshot from './AdvancedFilter.snapshot'
import AdvancedFilterButtonSnapshot from './AdvancedFilterButton.snapshot'
import AvatarSnapshot from './Avatar.snapshot'
import BadgeSnapshot from './Badge.snapshot'
import DataTableSnapshot from './DataTable.snapshot'
import FilterGroupSnapshot from './FilterGroup.snapshot'
import FilterRowSnapshot from './FilterRow.snapshot'
import PopoverSnapshot from './Popover.snapshot'
import SimpleFilterSnapshot from './SimpleFilter.snapshot'

// Version timestamp - changes on each update to trigger hot reload
export const snapshotsVersion = 1764777201456

// Export all snapshots
export { AddFilterButtonSnapshot, AdvancedFilterSnapshot, AdvancedFilterButtonSnapshot, AvatarSnapshot, BadgeSnapshot, DataTableSnapshot, FilterGroupSnapshot, FilterRowSnapshot, PopoverSnapshot, SimpleFilterSnapshot }

// Export as snapshots object (for passing to LunagraphEditor)
export const snapshots: Record<string, ComponentType<any>> = {
  AddFilterButtonSnapshot,
  AdvancedFilterSnapshot,
  AdvancedFilterButtonSnapshot,
  AvatarSnapshot,
  BadgeSnapshot,
  DataTableSnapshot,
  FilterGroupSnapshot,
  FilterRowSnapshot,
  PopoverSnapshot,
  SimpleFilterSnapshot
}
