// Auto-generated by @lunagraph/dev-server - do not edit manually
// This file is updated when snapshots are created or modified

import type { ComponentType } from 'react'

// Version timestamp - changes on each update to trigger hot reload
export const snapshotsVersion = 1

// Export as snapshots object (for passing to LunagraphEditor)
export const snapshots: Record<string, ComponentType<any>> = {}
