'use client'

import '@lunagraph/editor/styles.css';
import { LunagraphEditor, LUCIDE_PROPS_SCHEMA, FEElement } from "@lunagraph/editor";
import * as lunagraph from '../../.lunagraph/components';
// Import snapshots - generated by dev-server when editing components
import { snapshots } from '../../.lunagraph/snapshots';
import canvasData from '../../.lunagraph/canvases/canvas-1/canvas.json'
// Import Lucide icons
import * as LucideIcons from "lucide-react";

export default function Editor() {
  return (
    <LunagraphEditor
      {...lunagraph}
      components={lunagraph.components}
      snapshots={snapshots}
      initialElements={canvasData.elements as FEElement[]}
      readOnly
      iconLibraries={{
        "lucide-react": {
          icons: LucideIcons,
          displayName: "Lucide",
          defaultProps: { size: 24 },
          propsSchema: LUCIDE_PROPS_SCHEMA,
        }
      }}
    />
  )
}
